name: Deploy to WordPress.org

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Check version consistency
        run: ./scripts/check-version.sh

      - name: Export plugin (respecting .deployignore)
        run: |
          mkdir deploy
          EXCLUDES=$(cat .deployignore | sed '/^$/d' | sed '/^#/d' | sed 's/^/--exclude=/' | tr '\n' ' ')
          rsync -av $EXCLUDES ./ ./deploy/

      - name: Show plugin files
        run: |
          echo "🎯 deploy/ dir content:"
          find deploy/ -type f
